# Certbot => letsencrypt client
version: "3.8"
services:
  certbot:
    image: certbot/certbot:latest
    command: 
      [
        'certonly',
        '-n',
        '--force-renewal',
        '--email',
        'developerrynest@gmail.com',
        '--agree-tos',
        '--no-eff-email',
        '--webroot',
        '--webroot-path=/var/www/public/letsencrypt',
        '-d',
        'test1.rynestnetline.com',
        '-d',
        'test2.rynestnetline.com',
        # '-d',
        # 'api.lsp-ps.id',
        # '-d',
        # 'apito.qonstanta.com',
      ]
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/var/www/public/letsencrypt

