services:
  php-webman:
    build:
      context: ./
      dockerfile: ./docker/php-webman/phpwebman.docker
    container_name: aasi-phpwebman
    restart: unless-stopped
    tty: true
    ports:
      - 8787:8787
      - 3131:3131
      - 3232:3232
      - 8888:8888
    volumes:
      - ./webman:/webman
      # This prevents the first volume from overriding the contents (especially for vendor folder).
      - /webman/vendor
    depends_on:
      - nginx
      - redis

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/nginx.docker
    container_name: aasi-nginx
    restart: always
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./webman:/webman

  redis:
    image: redis:latest
    container_name: aasi-redis
    restart: on-failure
    tty: true
    ports:
      - 6379:6379
    working_dir: /data
    volumes:
      - redisdata:/data
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_HOST=127.0.0.1
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--replica-read-only",
        "no",
      ]

volumes:
  redisdata:
    driver: local