services:
  php-webman:
    build:
      context: ./
      dockerfile: ./docker/php-webman/phpwebman.docker
    container_name: api-aasi
    restart: unless-stopped
    tty: true
    ports:
      - 8787:8787
    volumes:
      - ./webman:/webman
